name: RV Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build
      run: echo "RV Build Successful"

    - name: Deploy
      run: echo "RV Deploy Successful"
